name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: deploy to Hugging Face
      uses: nateraw/huggingface-sync-action@v0.0.5
      with:
        github_repo_id: ttt246/Chatbot-AI-Safety-Test
        huggingface_repo_id: happygold/safetyai
        hf_token: ${{ secrets.HF_TOKEN }}
        repo_type: 'space'
        space_sdk: 'static'
